title: Helen Soremekun
description: Customer-focused data scientist specialising in churn, CLV, experimentation, and AI-assisted decision systems.
logo: imgfolder/pprofile.jpeg
#description: text below image
theme: jekyll-theme-minimal
show_downloads: false

